### ISSUE TITLE
Two line title syntax not working

### ISSUE THREAD

**Issue by glebovitz** [asciidoctor/sublimetext-asciidoc#6]
Description:

Both two line and one line titles are supported in asciidoctor, however they are not parsed correctly in the Sublime test Asciidoctor plugin.

The syntax parser / highlighter should not fail to parse documents that are in proper Asciidoctor accepted formats, even though the two line title format is not documented.

What I tried to do

I tried to edit a document using the title format

```
My Document Title
=================
```

What I expected to happen

The syntax highlighter in the asciidoctor pluginn would highlight the two line title, or at least accept the syntax of the two line titile.

What actually happened

The syntax highlighter identified the two line format as an error and failed to properly highlight the remainder of the document.

Recommended Change

Change the Asciidoctor plugin to accept the two line document title format, or at least not generate an error when the two line format is used.

Why this is important

Organizations who have built their documentation standards on Asciidoc, have specified the two line format as part of their standards. Not supporting this important Asciidoc feature, renders the plugin useless in these organizations.

**Comment by jirutka** [comment]
The two line title syntax is already deprecated in Asciidoctor (for several years) and I don't like increasing complexity by supporting long-time deprecated features. Organisations should update their standards to be up-to-date with tools they use.

Moreover, the highlighting syntax definition should be rewritten to use new SublimeText syntax format. The old one is very limited and insufficient for AsciiDoc syntax. However, I don't have time/resources to do it now.

**Comment by hupfdule** [comment]
> The two line title syntax is already deprecated in Asciidoctor (for several years)

Hi,

can you point me to some information where it is stated that two line title syntax is deprecated? I didn't find such a statement anywhere.
